version: "3.5"

services:
  redis-migration:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 1s
      retries: 10
    ports:
      - "6379:6379"